### ISSUE TITLE
virt-builder

### ISSUE THREAD

**Issue by timhughes** [ikke-t/virt-installs#1]
Saw your comment https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1031#issuecomment-626507530 and thought you may be interested in this if you haven't seen it before. It is for customizing a image build similar to packer but for libvirt specifically. I am not affiliated in any way :-)

http://libguestfs.org/virt-builder.1.html

```
thughes@krypton [0] $ virt-builder centos-8.0  --update  --firstboot-command 'dnf -y --best update'
[   0.6] Downloading: http://builder.libguestfs.org/centos-8.0.xz
[   2.1] Planning how to build this image
[   2.1] Uncompressing
[   6.8] Opening the new disk
[  13.1] Setting a random seed
[  13.1] Updating packages
[ 252.4] Installing firstboot command: dnf -y --best update
[ 252.6] Setting passwords
virt-builder: Setting random password of root to XXXXXXXXXXXX
[ 255.0] Finishing off
                   Output file: centos-8.0.img
                   Output size: 6.0G
                 Output format: raw
            Total usable space: 5.3G
                    Free space: 3.8G (70%)

thughes@krypton [0] $ 
```
Once you have an image you can just start it up with 
```
thughes@krypton [0] $ virt-install --name Centos8 --os-variant rhel8-unknown --memory 4096 --vcpus 2 --import --disk=./centos-8.0.img --noautoconsole

Starting install...
Domain creation completed.
thughes@krypton [0] $ 
```

**Comment by ikke-t** [comment]
Thanks for reminder, I used that years ago, but forgot about it. There is also modern GUI solution, if someone needs such. It let's you create all different types of templates for cloud and VM systems. It uses the Cockpit project for GUI:

https://developers.redhat.com/blog/2019/05/08/red-hat-enterprise-linux-8-image-builder-building-custom-system-images/

Well, not just GUI, but also cmdline.
